<?php

namespace AppBundle\Repository;

/**
 * SpecialityIncidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialityIncidentRepository extends \Doctrine\ORM\EntityRepository
{
}
