<?php

namespace AppBundle\Repository;

/**
 * SpecilityTechnicianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecilityTechnicianRepository extends \Doctrine\ORM\EntityRepository
{
}
