<?php

namespace AppBundle\Repository;

/**
 * TechnicianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicianRepository extends \Doctrine\ORM\EntityRepository
{
}
