<?php

namespace AppBundle\Repository;

/**
 * TypeSpecialityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSpecialityRepository extends \Doctrine\ORM\EntityRepository
{
}
