security: 
    encoders:
        AppBundle\Entity\Customer:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 4
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        user_provider:
            entity:
                class: AppBundle\Entity\Customer
                property: username


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false


        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                provider: user_provider
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
#            #anonymous: ~
#            #http_basic:
#            #    realm: "Secured Demo Area"

        oauth_authorize:
            pattern:    ^/oauth/v2/auth 
            anonymous: true
            security:     false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true

    access_control:
        # You can omit this if /api can be accessed both authenticated and anonymously
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }


## To get started with security, check out the documentation:
## https://symfony.com/doc/current/security.html
#security:
#    encoders:
#        AppBundle\Entity\User:
#            algorithm: bcrypt
#            cost: 4
#    role_hierarchy:
#        ROLE_ADMIN: ROLE_PRO
#        ROLE_PRO: ROLE_PERSON
#
#    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#    providers:
#        user_provider:
#            entity:
#                class: AppBundle\Entity\User
#                property: login
#        in_memory:
#            memory: ~
#
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#        user_area:
#            pattern: ^/user-secure
#            http_basic: ~
#            logout:
#                path: user_logout
#                target: /
#            provider: user_provider
#            context: my_context
#        main:
#            anonymous: ~
#            # activate different ways to authenticate
#
#            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#            #http_basic: ~
#
#            # https://symfony.com/doc/current/security/form_login_setup.html
#            #form_login: ~
#    access_control:
#        - { path: ^/user-secure, roles: ROLE_PERSON }
#        - { path: ^/pro, roles: ROLE_PRO }
#        - { path: ^/admin, roles: ROLE_ADMIN }